const routing = {
  home: '/',
  services: {
    order: '/services/kak-sdelat-zakaz',
    payVariants: '/services/sposob-oplaty',
    shipping: '/services/dostavka',
    productBack: '/services/vozvrat-tovara',
    moneyBack: '/services/vozvrat-denezhnyh-sredstv',
    salingRules: '/services/pravila-prodazhi',
    serviceRules: '/services/pravila-polzovaniya-torgovoi-ploshadkoi',
    faq: '/services/voprosy-i-otvety',
  },
  login: '/login',
  account: {
    index: '/account',
    favorite: '/account/favorite',
    orders: '/account/orders',
    support: '/account/support',
    reviews: '/account/reviews',
    wallet: '/account/wallet',
    profile: '/account/profile',
    shipping: '/account/shipping',
    sale: '/account/sale',
    cards: '/account/cards',
    cheki: '/account/cheki',
    brends: '/account/brends',
  },
  basket: '/basket',
}
export default routing
